---
title: "Data"
output: github_document
author: Jingya Yu, Landi Guo, Fengdi Zhang, Meng Fang, Yixuan Jiao
date: "2022-11-11"
---

```{r}
library(tidyverse)
library(dict)
```


```{r}
happiness_2021 <- read_csv("data/world-happiness-report-2021.csv") %>% janitor::clean_names()
happiness_pre_2021 <- read_csv("data/world-happiness-report.csv") %>% janitor::clean_names()

happiness_2021 <-
  happiness_2021 %>%
  select(country_name:ladder_score,logged_gdp_per_capita:perceptions_of_corruption) %>%
  mutate(year = 2021) 

happiness_pre_2021 <-
  happiness_pre_2021 %>%
  select(-positive_affect,-negative_affect) %>%
  #mutate(regional_indicator = NA) %>%
  rename("ladder_score" = "life_ladder", 
         "logged_gdp_per_capita" = "log_gdp_per_capita",
         "healthy_life_expectancy" = "healthy_life_expectancy_at_birth")

happiness_2021 <- 
  happiness_2021 %>%
  nest(data1 = ladder_score:year)
happiness_pre_2021 <- 
  happiness_pre_2021 %>%
  nest(data2 = year:perceptions_of_corruption)
df <- 
  happiness_2021 %>%
  left_join(happiness_pre_2021) %>%
  mutate(data = map2(data1,data2,bind_rows)) %>%
  select(-data1,-data2) %>%
  unnest(data) %>%
  drop_na() %>%
  relocate(country_name,regional_indicator,year) %>%
  arrange(country_name,regional_indicator,-year)
```

```{r}
write_csv(df, "Data/happiness.csv")
```

```{r}
country_to_region = dict()

for (i in 1:nrow(happiness_2021)) {
  country = happiness_2021[i, ]$country_name
  region = happiness_2021[i, ]$regional_indicator
  country_to_region[[country]] = region
}

f = function(country){
  country_to_region[[country]]
}
```

```{r}
df = 
  df %>%
  mutate(regional_indicator = map(country_name, f)) %>%
  drop_na()
```


