---
title: "Geospatial Analysis"
output: html_document
---

```{r}
library(ggplot2)
library(tidyverse)
library(plotly)
```


```{r}
iso_code <- 
  read.csv("https://raw.githubusercontent.com/plotly/datasets/master/2014_world_gdp_with_codes.csv") %>%
  janitor::clean_names() %>%
  rename(country_name = country) %>%
  select(-gdp_billions) %>%
  add_row(country_name = "Palestinian Territories", code = "PSE")
```

```{r}
happy <- 
  read_csv('Data/happiness.csv') %>%
  filter(year != 2005) %>%
  group_by(country_name) %>%
  summarise(mean_ladder_score = mean(ladder_score))
```

```{r}
happy_name <- unique(happy$country_name)
name <- unique(iso_code$country_name)
diff_name <- setdiff(happy_name,name)
code_name <- c("Congo, Republic of the","Gambia, The", "Hong Kong", "Cote d'Ivoire" ,"Burma", "Cyprus", "Macedonia", "Korea, South", "Taiwan")
for (i in 1:length(code_name)){
  iso_code$country_name[iso_code$country_name == code_name[i]] <- diff_name[i]
}
```

```{r}
happy <- left_join(happy,iso_code)
```

```{r}
g <- list(projection = list(type = ('orthographic')))

fig <- plot_ly(happy, type='choropleth', locations=happy$code, z=happy$mean_ladder_score, text=happy$country_name,colorscale = "Viridis")

fig %>% layout(geo = g)
```





