---
title: "World Happiness Analysis"
output: 
  html_document:
    toc: TRUE
    toc_float: TRUE
---

# Screen Cast
video link here


# Summary of Our Project
We use the data set from [kaggle](https://www.kaggle.com/datasets/ajaypalsinghlo/world-happiness-report-2021?resource=download&select=world-happiness-report.csv), trying to explore the relationship between the happiness ladder score and other social factors.

In the exploratory analysis part, we:

- Summaries the basic statistics over variables.
- Visually analyse the happiness ladder score and other metrics over different region.

We also perform statistical analysis including:

- Statistical test comparing mean ladder score over regions, pre/post covid period, difference in social factors and distribution of ladder score over happy/unhappy region.
- Regression analysis selecting the optimal subset of social factors that help us understand their relationships with happiness ladder score.
- Principle Component Analysis.

For our reader to freely explore our data and try to understand our model, we provide a interactive shiny app for people to:

- Try how different values to see how do they affect the ladder score
- Compare user selected variables over different countries/regions
- Check associations between each pair of factors.

Final report can be access [here](Report.html) or there is an entry on the right corner.
Detail code and output of each section is in the navigation bar.

# Members
Jingya Yu

Landi Guo

Fengdi Zhang

Meng Fang

Yixuan Jiao
